# Projet
site_name: jenkins.stallaf.net
site_url: https://jenkins.stallaf.net/
site_author: SF aka stallaf
site_description: Traduction en français de la documentation de JENKINS.

# Dépôt
repo_url: https://github.com/stallaf/traduction-en-francais-de-la-documentation-de-JENKINS
repo_name: stallaf/traduction-en-francais-de-la-documentation-de-JENKINS

# Thème
theme: 
  name: material
  language: fr
  logo: assets/avatar100px.jpg
  favicon: assets/favicon.ico
  palette:
  # Mode sombre
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mode sombre
      accent: deep purple
    # Mode clair
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mode clair
      accent: deep orange
  font:
    code: Roboto Mono
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

# Personnalisation
extra:
  version:
    provider: mike
    alias: true
    default:
      - latest
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
  - tables

# Plugins
plugins:
  - search
  - git-authors

# Copyright
copyright: Copyright &copy; 2025 SF aka stallaf

# Navigation
nav:
  - index.md 
  - Manuel d'utilisation:
    - Présentation: manuel-utilisateur-presentation.md
  - Installation Jenkins:
    - Présentation: installation-presentation.md
    - Docker: installation-docker.md
    - Kubernetes: installation-kubernetes.md
    - Linux: installation-linux.md
    - macOS: installation-macos.md
    - Windows: installation-windows.md
    - Autres systèmes: installation-autres-systemes.md
    - fichier WAR: installation-war.md
    - Autres conteneurs de servlet: installation-autres-conteneurs.md
    - Installations hors ligne: installation-hors-ligne.md
    - Paramètres initiaux: installation-parametres-initiaux.md
  - Informations sur la plateforme:
    - Présentation: plateforme-presentation.md
    - Politique d'Assistance Java: plateforme-java.md
    - Politique d'Assistance Linux: plateforme-linux.md
    - Politique d'Assistance Windows: plateforme-windows.md
    - Compatibilité avec les Navigateurs: plateforme-navigateurs.md
    - Politique d'Assistance des Conteneurs Servlet: plateforme-servlet.md
    - Mise à niveau vers Java 17: plateforme-maj-java-17.md
    - Mise à niveau vers Java 21: plateforme-maj-java-21.md
  - Utilisation de Jenkins:
    - Présentation: utilisation-presentation.md
    - Meilleures Pratiques: utilisation-meilleures-pratiques.md
    - Travailler avec des Projets: utilisation-projets.md
    - Utilisation des Identifiants: utilisation-identifiants.md
    - Palette de Commandes: utilisation-palette.md
    - Référencer un autre projet par son nom: utilisation-autre-projet-par-son-nom.md
    - Abandonner une compilation: utilisation-abandonner-une-compilation.md
    - Empreintes Digitales: utilisation-empreintes-digitales.md
    - Utilisation de la langue locale: utilisation-langue-locale.md
    - Changer le fuseau horaire: utilisation-fuseau-horaire.md
    - API d'Accès à Distance: utilisation-api-acces-a-distance.md
    - Insuffisance de l'Exécuteur: utilisation-insuffisance-executeur.md
    - Utilisation des agents Jenkins: utilisation-agents-jenkins.md
    - Utilisation de JMeter avec Jenkins: utilisation-jmeter.md
    - Stockage enfichable: utilisation-stockage-enfichable.md
  - Pipeline :
    - Présentation: pipeline-presentation.md
    - Commencer avec Pipeline: pipeline-commencer.md
    - Utilisation d'un Jenkinsfile: pipeline-jenkinsfile.md
    - Exécution des Pipelines: pipeline-execution.md
    - Branches et <i>Pull Requests</i>: pipeline-branches.md
    - Utilisation de Docker avec Pipeline : pipeline-docker.md
    - Extension avec des Bibliothèques Partagées: pipeline-bibliotheques-partagees.md
    - Outils de Développement dePpipelines: pipeline-outils.md
    - Syntaxe Pipeline: pipeline-syntaxe.md
    - Pipeline en tant que code: pipeline-comme-code.md
    - Meilleures pratiques concernant Pipelines: pipeline-meilleures-pratiques.md
    - Pipelines à échelle variable: pipeline-a-echelle-variable.md
    - Incompatibilités entre les méthodes CPS des pipelines: pipeline-incompatibilites-cps.md
  - Blue Ocean:
    - Présentation: blue-ocean-presentation.md
    - Commencez avec Blue Ocean: blue-ocean-commencer.md
    - Création d'un Pipeline: blue-ocean-creation-pipeline.md
    - Tableau de bord: blue-ocean-tableau-de-bord.md
    - Vue des activités: blue-ocean-vue-des-acitivites.md
    - Vue détaillée de l'exécution du Pipeline: blue-ocean-vue-detaillee-execution-pipeline .md
    - Editeur Pipeline: blue-ocean-editeur-pipeline.md
  - Gestion de Jenkinsfile:
    - Présentation: gestion-presentation.md
    - Configuration du système: gestion-configuration-du-systeme.md
    - Configuration en tant que code: gestion-cac.md
    - Gestion des Outils: gestion-outils.md
    - Gestion des Plugins: gestion-plugins.md
    - A propos de Jenkins: gestion-a-propos-de-jenkins.md
    - Information Système: gestion-information-systeme.md
    - Fonctionnalités Jenkins contrôlées par les propriétés système: gestion-proprietes-systeme.md
    - Modifier le fuseau horaire du système: gestion-modifier-le-fuseau-horaire.md
    - CLI Jenkins: gestion-cli.md
    - Console de Script: gestion-console.md
    - Script Groovy Hook: gestion-script-groovy-hook.md
    - Gestion des Noeuds: gestion-noeuds.md
    - Approbation du script en cours de traitement: gestion-approbation-du-script-en-cours-de-traitement.md
    - Utilisateurs: gestion-utilisateurs.md
    - Thèmes pour l'interface utilisateur: gestion-themes-interface.md
    - Contenu utilisateur: gestion-contenu-utilisateur.md
    - Processus de Génération à partir de la Compilation: gestion-generation.md
  - Sécuriser Jenkinsfile:
    - Présentation: securite-presentation.md
    - Contrôle d'Accès: securite-controle-acces.md
    - Sécuriser Jenkins: securite-securiser-jenkins.md
    - Gestion de la Sécurité: securite-gestion.md
    - Isolation du Contrôleur: securite-isolation-du-controleur.md
    - Sécurisation des compilations: securite-securisation-des-compilations.md
    - Protection CSRF: securite-protection-csrf.md
    - Rendu du Contenu Utilisateur: securite-rendu-du-contenu-utilisateur.md
    - Contrôle d'Accès pour les Constructions: securite-controle-acces-construction.md
    - Gestion des variables d'environnement: securite-variables-environnement.md
    - Formatage des balises: securite-formatage-des-balises.md
    - Sécurisation des informations d'identification SCM pour les dossiers d'organisation et les pipelines multibranches: securite-securisation-des-informations-identification.md
    - Services et ports exposés: securite-services-et-ports-exposes.md
    - Informations d'Identification: securite-informations-identification.md
  - Administration Système:
    - Présentation: administration-systeme-presentation.md
    - Sauvegarde/Restauration de Jenkins: administration-systeme-sauv-rest-jenkins.md
    - Surveillance de Jenkins: administration-systeme-surveillance-jenkins.md
    - Administration de Jenkins sur Kubernetes: administration-systeme-kubernetes.md
    - Gestion de Jenkins avec Chef: administration-systeme-chef.md
    - Gestion de Jenkins avec Puppet: administration-systeme-puppet.md 
    - Affichage des journaux: administration-systeme-journaux.md