# Projet
site_name: jenkins.stallaf.net
site_url: https://jenkins.stallaf.net/
site_author: SF aka stallaf
site_description: Traduction en français de la documentation de JENKINS.

# Dépôt
repo_url: https://github.com/stallaf/traduction-en-francais-de-la-documentation-de-JENKINS
repo_name: stallaf/traduction-en-francais-de-la-documentation-de-JENKINS

# Thème
theme: 
  name: material
  language: fr
  logo: assets/avatar100px.jpg
  favicon: assets/favicon.ico
  palette:
  # Mode sombre
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mode sombre
      accent: deep purple
    # Mode clair
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mode clair
      accent: deep orange
  font:
    code: Roboto Mono
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

# Personnalisation
extra:
  version:
    provider: mike
    alias: true
    default:
      - latest
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - tables

# Plugins
plugins:
  - search
  - git-authors

# Copyright
copyright: Copyright &copy; 2025 SF aka stallaf

# Navigation
nav:
  - index.md 
  - Manuel d'utilisation:
    - Présentation: manuel-utilisateur-presentation.md
  - Installation Jenkins:
    - Présentation: installation-presentation.md
    - Docker: installation-docker.md
    - Kubernetes: installation-kubernetes.md
    - Linux: installation-linux.md
    - macOS: installation-macos.md
    - Windows: installation-windows.md
    - Autres systèmes: installation-autres-systemes.md
    - fichier WAR: installation-war.md
    - Autres conteneurs de servlet: installation-autres-conteneurs.md
    - Installations hors ligne: installation-hors-ligne.md
    - Paramètres initiaux: installation-parametres-initiaux.md
  - Informations sur la plateforme:
    - Présentation: plateforme-presentation.md
    - Politique d'Assistance Java: plateforme-java.md
    - Politique d'Assistance Linux: plateforme-linux.md
    - Politique d'Assistance Windows: plateforme-windows.md
    - Compatibilité avec les Navigateurs: plateforme-navigateurs.md
    - Politique d'Assistance des Conteneurs Servlet: plateforme-servlet.md
    - Mise à niveau vers Java 17: plateforme-maj-java-17.md
    - Mise à niveau vers Java 21: plateforme-maj-java-21.md
  - Utilisation de Jenkins:
    - Présentation: utilisation-presentation.md
    - Meilleures Pratiques: utilisation-meilleures-pratiques.md
    - Travailler avec des Projets: utilisation-projets.md
    - Utilisation des Identifiants: utilisation-identifiants.md