site_name: jenkins.stallaf.net
site_url: https://jenkins.stallaf.net/
repo_url: https://github.com/stallaf/traduction-en-francais-de-la-documentation-de-JENKINS
repo_name: stallaf/traduction-en-francais-de-la-documentation-de-JENKINS
site_author: SF aka stallaf
site_description: Traduction en français de la documentation de JENKINS.

theme: 
  name: material
  language: fr
  logo: assets/avatar100px.jpg
  favicon: assets/favicon.ico
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      accent: deep purple
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      accent: deep orange
  font:
    code: Red Hat Mono

extra_css:
  - stylesheets/extra.css

markdown_extensions:
# Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  version:
    provider: mike
    alias: true
    default:
      - latest

plugins:
  - git-committers:
    enabled: true
    repository: stallaf/traduction-en-francais-de-la-documentation-de-JENKINS
    branch: main
    token: !ENV GH_TOKEN
  - git-revision-date-localized:
    type: date
    fallback_to_build_date: false
    enable_creation_date: true
    enabled: true
  - glightbox:
    touchNavigation: false
    loop: false
    effect: zoom
    width: 100%
    height: auto
    zoomable: true
    draggable: true
  - git-authors
  - search:
    separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

copyright: Copyright &copy; 2025 SF aka stallaf

nav:
  - index.md 
  - Manuel d'utilisation:
    - Présentation: manuel-utilisateur-presentation.md
    - Installation Jenkins: installation-jenkins.md